CREATE TABLE urls (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE,
    created_at TIMESTAMP 
);

CREATE TABLE urls_checks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url_id BIGINT,
    status_code BIGINT,
    h1 VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP
);

